server:
  port: 8761
#设置服务验证的账号密码

security:
  user:
    name: user
    password: password123
eureka:
  client:
    register-with-eureka: false #当作eureka当作一个Server 不是当作一个Client
    fetch-registry: false
    service-url:
      defaultZone : http://user:password123@localhost:8761/eureka #eureka服务器验证需要您输入账号密码

