server:
  port: 8001
spring:
  application:
    name: microservice-provider-user #使用Spring Application提供的方法指定微服务名称
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           #指定数据源
    platform: h2                        #指定数据源类型
    schema: classpath:schema.sql        #指定h2数据库的建表脚本
    data: classpath:data.sql            #指定h2数据库的insert脚本
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hiberante.type.descriptor.sql.BasicBinder: TRACE
    org.hiberante.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch: DEBUG
#Eureka的到对应的服务器
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true #设置为ture 可以使用ip访问
    #通过自定义微服务的 ${spring.cloud.client.hostname} 本地及其名称
    #应用名 ：ip地址：端口
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}} 

  
        